/**
 * generated by Xtext 2.14.0
 */
package ru.spbstu.application.configurator.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Hold Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ru.spbstu.application.configurator.myDsl.HoldType#getFeatures <em>Features</em>}</li>
 * </ul>
 *
 * @see ru.spbstu.application.configurator.myDsl.MyDslPackage#getHoldType()
 * @model
 * @generated
 */
public interface HoldType extends EObject
{
  /**
   * Returns the value of the '<em><b>Features</b></em>' containment reference list.
   * The list contents are of type {@link ru.spbstu.application.configurator.myDsl.Type}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Features</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Features</em>' containment reference list.
   * @see ru.spbstu.application.configurator.myDsl.MyDslPackage#getHoldType_Features()
   * @model containment="true"
   * @generated
   */
  EList<Type> getFeatures();

} // HoldType
