/**
 * generated by Xtext 2.14.0
 */
package ru.spbstu.application.configurator.model.infoProject;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Delivery Channel Parameters</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ru.spbstu.application.configurator.model.infoProject.DeliveryChannelParameters#getFeature <em>Feature</em>}</li>
 * </ul>
 *
 * @see ru.spbstu.application.configurator.model.infoProject.InfoProjectPackage#getDeliveryChannelParameters()
 * @model
 * @generated
 */
public interface DeliveryChannelParameters extends EObject
{
  /**
   * Returns the value of the '<em><b>Feature</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.emf.ecore.EObject}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Feature</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Feature</em>' containment reference list.
   * @see ru.spbstu.application.configurator.model.infoProject.InfoProjectPackage#getDeliveryChannelParameters_Feature()
   * @model containment="true"
   * @generated
   */
  EList<EObject> getFeature();

} // DeliveryChannelParameters
