/**
 * generated by Xtext 2.14.0
 */
package ru.spbstu.application.configurator.model.infoProject;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see ru.spbstu.application.configurator.model.infoProject.InfoProjectFactory
 * @model kind="package"
 * @generated
 */
public interface InfoProjectPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "infoProject";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.spbstu.ru/application/configurator/model/InfoProject";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "infoProject";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  InfoProjectPackage eINSTANCE = ru.spbstu.application.configurator.model.infoProject.impl.InfoProjectPackageImpl.init();

  /**
   * The meta object id for the '{@link ru.spbstu.application.configurator.model.infoProject.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ru.spbstu.application.configurator.model.infoProject.impl.ModelImpl
   * @see ru.spbstu.application.configurator.model.infoProject.impl.InfoProjectPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Element</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ELEMENT = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ru.spbstu.application.configurator.model.infoProject.impl.VersionImpl <em>Version</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ru.spbstu.application.configurator.model.infoProject.impl.VersionImpl
   * @see ru.spbstu.application.configurator.model.infoProject.impl.InfoProjectPackageImpl#getVersion()
   * @generated
   */
  int VERSION = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERSION__NAME = 0;

  /**
   * The number of structural features of the '<em>Version</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERSION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ru.spbstu.application.configurator.model.infoProject.impl.FeatureNameImpl <em>Feature Name</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ru.spbstu.application.configurator.model.infoProject.impl.FeatureNameImpl
   * @see ru.spbstu.application.configurator.model.infoProject.impl.InfoProjectPackageImpl#getFeatureName()
   * @generated
   */
  int FEATURE_NAME = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE_NAME__NAME = 0;

  /**
   * The number of structural features of the '<em>Feature Name</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE_NAME_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ru.spbstu.application.configurator.model.infoProject.impl.ApplicationImpl <em>Application</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ru.spbstu.application.configurator.model.infoProject.impl.ApplicationImpl
   * @see ru.spbstu.application.configurator.model.infoProject.impl.InfoProjectPackageImpl#getApplication()
   * @generated
   */
  int APPLICATION = 3;

  /**
   * The feature id for the '<em><b>Features1</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APPLICATION__FEATURES1 = 0;

  /**
   * The feature id for the '<em><b>Features</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APPLICATION__FEATURES = 1;

  /**
   * The feature id for the '<em><b>Feature</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APPLICATION__FEATURE = 2;

  /**
   * The number of structural features of the '<em>Application</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int APPLICATION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link ru.spbstu.application.configurator.model.infoProject.impl.TenantImpl <em>Tenant</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ru.spbstu.application.configurator.model.infoProject.impl.TenantImpl
   * @see ru.spbstu.application.configurator.model.infoProject.impl.InfoProjectPackageImpl#getTenant()
   * @generated
   */
  int TENANT = 4;

  /**
   * The feature id for the '<em><b>Features1</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TENANT__FEATURES1 = 0;

  /**
   * The number of structural features of the '<em>Tenant</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TENANT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ru.spbstu.application.configurator.model.infoProject.impl.HoldImpl <em>Hold</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ru.spbstu.application.configurator.model.infoProject.impl.HoldImpl
   * @see ru.spbstu.application.configurator.model.infoProject.impl.InfoProjectPackageImpl#getHold()
   * @generated
   */
  int HOLD = 5;

  /**
   * The feature id for the '<em><b>Features1</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HOLD__FEATURES1 = 0;

  /**
   * The feature id for the '<em><b>Features</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HOLD__FEATURES = 1;

  /**
   * The number of structural features of the '<em>Hold</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HOLD_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link ru.spbstu.application.configurator.model.infoProject.impl.ArchiveTypeImpl <em>Archive Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ru.spbstu.application.configurator.model.infoProject.impl.ArchiveTypeImpl
   * @see ru.spbstu.application.configurator.model.infoProject.impl.InfoProjectPackageImpl#getArchiveType()
   * @generated
   */
  int ARCHIVE_TYPE = 6;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARCHIVE_TYPE__VALUE = 0;

  /**
   * The number of structural features of the '<em>Archive Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARCHIVE_TYPE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ru.spbstu.application.configurator.model.infoProject.impl.CategoryImpl <em>Category</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ru.spbstu.application.configurator.model.infoProject.impl.CategoryImpl
   * @see ru.spbstu.application.configurator.model.infoProject.impl.InfoProjectPackageImpl#getCategory()
   * @generated
   */
  int CATEGORY = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CATEGORY__NAME = 0;

  /**
   * The number of structural features of the '<em>Category</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CATEGORY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ru.spbstu.application.configurator.model.infoProject.impl.DescriptionImpl <em>Description</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ru.spbstu.application.configurator.model.infoProject.impl.DescriptionImpl
   * @see ru.spbstu.application.configurator.model.infoProject.impl.InfoProjectPackageImpl#getDescription()
   * @generated
   */
  int DESCRIPTION = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESCRIPTION__NAME = 0;

  /**
   * The number of structural features of the '<em>Description</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESCRIPTION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ru.spbstu.application.configurator.model.infoProject.impl.MCSImpl <em>MCS</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ru.spbstu.application.configurator.model.infoProject.impl.MCSImpl
   * @see ru.spbstu.application.configurator.model.infoProject.impl.InfoProjectPackageImpl#getMCS()
   * @generated
   */
  int MCS = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MCS__NAME = 0;

  /**
   * The number of structural features of the '<em>MCS</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MCS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ru.spbstu.application.configurator.model.infoProject.impl.TypeImpl <em>Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ru.spbstu.application.configurator.model.infoProject.impl.TypeImpl
   * @see ru.spbstu.application.configurator.model.infoProject.impl.InfoProjectPackageImpl#getType()
   * @generated
   */
  int TYPE = 10;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__VALUE = 0;

  /**
   * The number of structural features of the '<em>Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ru.spbstu.application.configurator.model.infoProject.impl.HoldTypeImpl <em>Hold Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ru.spbstu.application.configurator.model.infoProject.impl.HoldTypeImpl
   * @see ru.spbstu.application.configurator.model.infoProject.impl.InfoProjectPackageImpl#getHoldType()
   * @generated
   */
  int HOLD_TYPE = 11;

  /**
   * The feature id for the '<em><b>Features</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HOLD_TYPE__FEATURES = 0;

  /**
   * The number of structural features of the '<em>Hold Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HOLD_TYPE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ru.spbstu.application.configurator.model.infoProject.enumOfArchiveType <em>enum Of Archive Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ru.spbstu.application.configurator.model.infoProject.enumOfArchiveType
   * @see ru.spbstu.application.configurator.model.infoProject.impl.InfoProjectPackageImpl#getenumOfArchiveType()
   * @generated
   */
  int ENUM_OF_ARCHIVE_TYPE = 12;

  /**
   * The meta object id for the '{@link ru.spbstu.application.configurator.model.infoProject.enumOfTypes <em>enum Of Types</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ru.spbstu.application.configurator.model.infoProject.enumOfTypes
   * @see ru.spbstu.application.configurator.model.infoProject.impl.InfoProjectPackageImpl#getenumOfTypes()
   * @generated
   */
  int ENUM_OF_TYPES = 13;


  /**
   * Returns the meta object for class '{@link ru.spbstu.application.configurator.model.infoProject.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see ru.spbstu.application.configurator.model.infoProject.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link ru.spbstu.application.configurator.model.infoProject.Model#getElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Element</em>'.
   * @see ru.spbstu.application.configurator.model.infoProject.Model#getElement()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Element();

  /**
   * Returns the meta object for class '{@link ru.spbstu.application.configurator.model.infoProject.Version <em>Version</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Version</em>'.
   * @see ru.spbstu.application.configurator.model.infoProject.Version
   * @generated
   */
  EClass getVersion();

  /**
   * Returns the meta object for the attribute '{@link ru.spbstu.application.configurator.model.infoProject.Version#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ru.spbstu.application.configurator.model.infoProject.Version#getName()
   * @see #getVersion()
   * @generated
   */
  EAttribute getVersion_Name();

  /**
   * Returns the meta object for class '{@link ru.spbstu.application.configurator.model.infoProject.FeatureName <em>Feature Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Feature Name</em>'.
   * @see ru.spbstu.application.configurator.model.infoProject.FeatureName
   * @generated
   */
  EClass getFeatureName();

  /**
   * Returns the meta object for the attribute '{@link ru.spbstu.application.configurator.model.infoProject.FeatureName#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ru.spbstu.application.configurator.model.infoProject.FeatureName#getName()
   * @see #getFeatureName()
   * @generated
   */
  EAttribute getFeatureName_Name();

  /**
   * Returns the meta object for class '{@link ru.spbstu.application.configurator.model.infoProject.Application <em>Application</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Application</em>'.
   * @see ru.spbstu.application.configurator.model.infoProject.Application
   * @generated
   */
  EClass getApplication();

  /**
   * Returns the meta object for the containment reference list '{@link ru.spbstu.application.configurator.model.infoProject.Application#getFeatures1 <em>Features1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Features1</em>'.
   * @see ru.spbstu.application.configurator.model.infoProject.Application#getFeatures1()
   * @see #getApplication()
   * @generated
   */
  EReference getApplication_Features1();

  /**
   * Returns the meta object for the containment reference list '{@link ru.spbstu.application.configurator.model.infoProject.Application#getFeatures <em>Features</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Features</em>'.
   * @see ru.spbstu.application.configurator.model.infoProject.Application#getFeatures()
   * @see #getApplication()
   * @generated
   */
  EReference getApplication_Features();

  /**
   * Returns the meta object for the containment reference list '{@link ru.spbstu.application.configurator.model.infoProject.Application#getFeature <em>Feature</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Feature</em>'.
   * @see ru.spbstu.application.configurator.model.infoProject.Application#getFeature()
   * @see #getApplication()
   * @generated
   */
  EReference getApplication_Feature();

  /**
   * Returns the meta object for class '{@link ru.spbstu.application.configurator.model.infoProject.Tenant <em>Tenant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tenant</em>'.
   * @see ru.spbstu.application.configurator.model.infoProject.Tenant
   * @generated
   */
  EClass getTenant();

  /**
   * Returns the meta object for the containment reference list '{@link ru.spbstu.application.configurator.model.infoProject.Tenant#getFeatures1 <em>Features1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Features1</em>'.
   * @see ru.spbstu.application.configurator.model.infoProject.Tenant#getFeatures1()
   * @see #getTenant()
   * @generated
   */
  EReference getTenant_Features1();

  /**
   * Returns the meta object for class '{@link ru.spbstu.application.configurator.model.infoProject.Hold <em>Hold</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Hold</em>'.
   * @see ru.spbstu.application.configurator.model.infoProject.Hold
   * @generated
   */
  EClass getHold();

  /**
   * Returns the meta object for the containment reference list '{@link ru.spbstu.application.configurator.model.infoProject.Hold#getFeatures1 <em>Features1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Features1</em>'.
   * @see ru.spbstu.application.configurator.model.infoProject.Hold#getFeatures1()
   * @see #getHold()
   * @generated
   */
  EReference getHold_Features1();

  /**
   * Returns the meta object for the containment reference list '{@link ru.spbstu.application.configurator.model.infoProject.Hold#getFeatures <em>Features</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Features</em>'.
   * @see ru.spbstu.application.configurator.model.infoProject.Hold#getFeatures()
   * @see #getHold()
   * @generated
   */
  EReference getHold_Features();

  /**
   * Returns the meta object for class '{@link ru.spbstu.application.configurator.model.infoProject.ArchiveType <em>Archive Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Archive Type</em>'.
   * @see ru.spbstu.application.configurator.model.infoProject.ArchiveType
   * @generated
   */
  EClass getArchiveType();

  /**
   * Returns the meta object for the attribute '{@link ru.spbstu.application.configurator.model.infoProject.ArchiveType#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see ru.spbstu.application.configurator.model.infoProject.ArchiveType#getValue()
   * @see #getArchiveType()
   * @generated
   */
  EAttribute getArchiveType_Value();

  /**
   * Returns the meta object for class '{@link ru.spbstu.application.configurator.model.infoProject.Category <em>Category</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Category</em>'.
   * @see ru.spbstu.application.configurator.model.infoProject.Category
   * @generated
   */
  EClass getCategory();

  /**
   * Returns the meta object for the attribute '{@link ru.spbstu.application.configurator.model.infoProject.Category#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ru.spbstu.application.configurator.model.infoProject.Category#getName()
   * @see #getCategory()
   * @generated
   */
  EAttribute getCategory_Name();

  /**
   * Returns the meta object for class '{@link ru.spbstu.application.configurator.model.infoProject.Description <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Description</em>'.
   * @see ru.spbstu.application.configurator.model.infoProject.Description
   * @generated
   */
  EClass getDescription();

  /**
   * Returns the meta object for the attribute '{@link ru.spbstu.application.configurator.model.infoProject.Description#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ru.spbstu.application.configurator.model.infoProject.Description#getName()
   * @see #getDescription()
   * @generated
   */
  EAttribute getDescription_Name();

  /**
   * Returns the meta object for class '{@link ru.spbstu.application.configurator.model.infoProject.MCS <em>MCS</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>MCS</em>'.
   * @see ru.spbstu.application.configurator.model.infoProject.MCS
   * @generated
   */
  EClass getMCS();

  /**
   * Returns the meta object for the attribute '{@link ru.spbstu.application.configurator.model.infoProject.MCS#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ru.spbstu.application.configurator.model.infoProject.MCS#getName()
   * @see #getMCS()
   * @generated
   */
  EAttribute getMCS_Name();

  /**
   * Returns the meta object for class '{@link ru.spbstu.application.configurator.model.infoProject.Type <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type</em>'.
   * @see ru.spbstu.application.configurator.model.infoProject.Type
   * @generated
   */
  EClass getType();

  /**
   * Returns the meta object for the attribute '{@link ru.spbstu.application.configurator.model.infoProject.Type#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see ru.spbstu.application.configurator.model.infoProject.Type#getValue()
   * @see #getType()
   * @generated
   */
  EAttribute getType_Value();

  /**
   * Returns the meta object for class '{@link ru.spbstu.application.configurator.model.infoProject.HoldType <em>Hold Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Hold Type</em>'.
   * @see ru.spbstu.application.configurator.model.infoProject.HoldType
   * @generated
   */
  EClass getHoldType();

  /**
   * Returns the meta object for the containment reference list '{@link ru.spbstu.application.configurator.model.infoProject.HoldType#getFeatures <em>Features</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Features</em>'.
   * @see ru.spbstu.application.configurator.model.infoProject.HoldType#getFeatures()
   * @see #getHoldType()
   * @generated
   */
  EReference getHoldType_Features();

  /**
   * Returns the meta object for enum '{@link ru.spbstu.application.configurator.model.infoProject.enumOfArchiveType <em>enum Of Archive Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>enum Of Archive Type</em>'.
   * @see ru.spbstu.application.configurator.model.infoProject.enumOfArchiveType
   * @generated
   */
  EEnum getenumOfArchiveType();

  /**
   * Returns the meta object for enum '{@link ru.spbstu.application.configurator.model.infoProject.enumOfTypes <em>enum Of Types</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>enum Of Types</em>'.
   * @see ru.spbstu.application.configurator.model.infoProject.enumOfTypes
   * @generated
   */
  EEnum getenumOfTypes();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  InfoProjectFactory getInfoProjectFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link ru.spbstu.application.configurator.model.infoProject.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ru.spbstu.application.configurator.model.infoProject.impl.ModelImpl
     * @see ru.spbstu.application.configurator.model.infoProject.impl.InfoProjectPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Element</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__ELEMENT = eINSTANCE.getModel_Element();

    /**
     * The meta object literal for the '{@link ru.spbstu.application.configurator.model.infoProject.impl.VersionImpl <em>Version</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ru.spbstu.application.configurator.model.infoProject.impl.VersionImpl
     * @see ru.spbstu.application.configurator.model.infoProject.impl.InfoProjectPackageImpl#getVersion()
     * @generated
     */
    EClass VERSION = eINSTANCE.getVersion();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VERSION__NAME = eINSTANCE.getVersion_Name();

    /**
     * The meta object literal for the '{@link ru.spbstu.application.configurator.model.infoProject.impl.FeatureNameImpl <em>Feature Name</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ru.spbstu.application.configurator.model.infoProject.impl.FeatureNameImpl
     * @see ru.spbstu.application.configurator.model.infoProject.impl.InfoProjectPackageImpl#getFeatureName()
     * @generated
     */
    EClass FEATURE_NAME = eINSTANCE.getFeatureName();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FEATURE_NAME__NAME = eINSTANCE.getFeatureName_Name();

    /**
     * The meta object literal for the '{@link ru.spbstu.application.configurator.model.infoProject.impl.ApplicationImpl <em>Application</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ru.spbstu.application.configurator.model.infoProject.impl.ApplicationImpl
     * @see ru.spbstu.application.configurator.model.infoProject.impl.InfoProjectPackageImpl#getApplication()
     * @generated
     */
    EClass APPLICATION = eINSTANCE.getApplication();

    /**
     * The meta object literal for the '<em><b>Features1</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference APPLICATION__FEATURES1 = eINSTANCE.getApplication_Features1();

    /**
     * The meta object literal for the '<em><b>Features</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference APPLICATION__FEATURES = eINSTANCE.getApplication_Features();

    /**
     * The meta object literal for the '<em><b>Feature</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference APPLICATION__FEATURE = eINSTANCE.getApplication_Feature();

    /**
     * The meta object literal for the '{@link ru.spbstu.application.configurator.model.infoProject.impl.TenantImpl <em>Tenant</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ru.spbstu.application.configurator.model.infoProject.impl.TenantImpl
     * @see ru.spbstu.application.configurator.model.infoProject.impl.InfoProjectPackageImpl#getTenant()
     * @generated
     */
    EClass TENANT = eINSTANCE.getTenant();

    /**
     * The meta object literal for the '<em><b>Features1</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TENANT__FEATURES1 = eINSTANCE.getTenant_Features1();

    /**
     * The meta object literal for the '{@link ru.spbstu.application.configurator.model.infoProject.impl.HoldImpl <em>Hold</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ru.spbstu.application.configurator.model.infoProject.impl.HoldImpl
     * @see ru.spbstu.application.configurator.model.infoProject.impl.InfoProjectPackageImpl#getHold()
     * @generated
     */
    EClass HOLD = eINSTANCE.getHold();

    /**
     * The meta object literal for the '<em><b>Features1</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HOLD__FEATURES1 = eINSTANCE.getHold_Features1();

    /**
     * The meta object literal for the '<em><b>Features</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HOLD__FEATURES = eINSTANCE.getHold_Features();

    /**
     * The meta object literal for the '{@link ru.spbstu.application.configurator.model.infoProject.impl.ArchiveTypeImpl <em>Archive Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ru.spbstu.application.configurator.model.infoProject.impl.ArchiveTypeImpl
     * @see ru.spbstu.application.configurator.model.infoProject.impl.InfoProjectPackageImpl#getArchiveType()
     * @generated
     */
    EClass ARCHIVE_TYPE = eINSTANCE.getArchiveType();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ARCHIVE_TYPE__VALUE = eINSTANCE.getArchiveType_Value();

    /**
     * The meta object literal for the '{@link ru.spbstu.application.configurator.model.infoProject.impl.CategoryImpl <em>Category</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ru.spbstu.application.configurator.model.infoProject.impl.CategoryImpl
     * @see ru.spbstu.application.configurator.model.infoProject.impl.InfoProjectPackageImpl#getCategory()
     * @generated
     */
    EClass CATEGORY = eINSTANCE.getCategory();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CATEGORY__NAME = eINSTANCE.getCategory_Name();

    /**
     * The meta object literal for the '{@link ru.spbstu.application.configurator.model.infoProject.impl.DescriptionImpl <em>Description</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ru.spbstu.application.configurator.model.infoProject.impl.DescriptionImpl
     * @see ru.spbstu.application.configurator.model.infoProject.impl.InfoProjectPackageImpl#getDescription()
     * @generated
     */
    EClass DESCRIPTION = eINSTANCE.getDescription();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DESCRIPTION__NAME = eINSTANCE.getDescription_Name();

    /**
     * The meta object literal for the '{@link ru.spbstu.application.configurator.model.infoProject.impl.MCSImpl <em>MCS</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ru.spbstu.application.configurator.model.infoProject.impl.MCSImpl
     * @see ru.spbstu.application.configurator.model.infoProject.impl.InfoProjectPackageImpl#getMCS()
     * @generated
     */
    EClass MCS = eINSTANCE.getMCS();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MCS__NAME = eINSTANCE.getMCS_Name();

    /**
     * The meta object literal for the '{@link ru.spbstu.application.configurator.model.infoProject.impl.TypeImpl <em>Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ru.spbstu.application.configurator.model.infoProject.impl.TypeImpl
     * @see ru.spbstu.application.configurator.model.infoProject.impl.InfoProjectPackageImpl#getType()
     * @generated
     */
    EClass TYPE = eINSTANCE.getType();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE__VALUE = eINSTANCE.getType_Value();

    /**
     * The meta object literal for the '{@link ru.spbstu.application.configurator.model.infoProject.impl.HoldTypeImpl <em>Hold Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ru.spbstu.application.configurator.model.infoProject.impl.HoldTypeImpl
     * @see ru.spbstu.application.configurator.model.infoProject.impl.InfoProjectPackageImpl#getHoldType()
     * @generated
     */
    EClass HOLD_TYPE = eINSTANCE.getHoldType();

    /**
     * The meta object literal for the '<em><b>Features</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HOLD_TYPE__FEATURES = eINSTANCE.getHoldType_Features();

    /**
     * The meta object literal for the '{@link ru.spbstu.application.configurator.model.infoProject.enumOfArchiveType <em>enum Of Archive Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ru.spbstu.application.configurator.model.infoProject.enumOfArchiveType
     * @see ru.spbstu.application.configurator.model.infoProject.impl.InfoProjectPackageImpl#getenumOfArchiveType()
     * @generated
     */
    EEnum ENUM_OF_ARCHIVE_TYPE = eINSTANCE.getenumOfArchiveType();

    /**
     * The meta object literal for the '{@link ru.spbstu.application.configurator.model.infoProject.enumOfTypes <em>enum Of Types</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ru.spbstu.application.configurator.model.infoProject.enumOfTypes
     * @see ru.spbstu.application.configurator.model.infoProject.impl.InfoProjectPackageImpl#getenumOfTypes()
     * @generated
     */
    EEnum ENUM_OF_TYPES = eINSTANCE.getenumOfTypes();

  }

} //InfoProjectPackage
