/**
 * generated by Xtext 2.14.0
 */
package ru.spbstu.application.configurator.model.validation;

import ru.spbstu.application.configurator.model.validation.AbstractInfoProjectValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class InfoProjectValidator extends AbstractInfoProjectValidator {
}
