/**
 * generated by Xtext 2.14.0
 */
package ru.spbstu.application.configurator.myDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import ru.spbstu.application.configurator.myDsl.Application;
import ru.spbstu.application.configurator.myDsl.ArchiveTipe;
import ru.spbstu.application.configurator.myDsl.FeatureName;
import ru.spbstu.application.configurator.myDsl.MyDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Application</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link ru.spbstu.application.configurator.myDsl.impl.ApplicationImpl#getFeatures1 <em>Features1</em>}</li>
 *   <li>{@link ru.spbstu.application.configurator.myDsl.impl.ApplicationImpl#getFeatures <em>Features</em>}</li>
 *   <li>{@link ru.spbstu.application.configurator.myDsl.impl.ApplicationImpl#getFeature <em>Feature</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ApplicationImpl extends MinimalEObjectImpl.Container implements Application
{
  /**
   * The cached value of the '{@link #getFeatures1() <em>Features1</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFeatures1()
   * @generated
   * @ordered
   */
  protected EList<FeatureName> features1;

  /**
   * The cached value of the '{@link #getFeatures() <em>Features</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFeatures()
   * @generated
   * @ordered
   */
  protected EList<ArchiveTipe> features;

  /**
   * The cached value of the '{@link #getFeature() <em>Feature</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFeature()
   * @generated
   * @ordered
   */
  protected EList<EObject> feature;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ApplicationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.APPLICATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<FeatureName> getFeatures1()
  {
    if (features1 == null)
    {
      features1 = new EObjectContainmentEList<FeatureName>(FeatureName.class, this, MyDslPackage.APPLICATION__FEATURES1);
    }
    return features1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<ArchiveTipe> getFeatures()
  {
    if (features == null)
    {
      features = new EObjectContainmentEList<ArchiveTipe>(ArchiveTipe.class, this, MyDslPackage.APPLICATION__FEATURES);
    }
    return features;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<EObject> getFeature()
  {
    if (feature == null)
    {
      feature = new EObjectContainmentEList<EObject>(EObject.class, this, MyDslPackage.APPLICATION__FEATURE);
    }
    return feature;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.APPLICATION__FEATURES1:
        return ((InternalEList<?>)getFeatures1()).basicRemove(otherEnd, msgs);
      case MyDslPackage.APPLICATION__FEATURES:
        return ((InternalEList<?>)getFeatures()).basicRemove(otherEnd, msgs);
      case MyDslPackage.APPLICATION__FEATURE:
        return ((InternalEList<?>)getFeature()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.APPLICATION__FEATURES1:
        return getFeatures1();
      case MyDslPackage.APPLICATION__FEATURES:
        return getFeatures();
      case MyDslPackage.APPLICATION__FEATURE:
        return getFeature();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.APPLICATION__FEATURES1:
        getFeatures1().clear();
        getFeatures1().addAll((Collection<? extends FeatureName>)newValue);
        return;
      case MyDslPackage.APPLICATION__FEATURES:
        getFeatures().clear();
        getFeatures().addAll((Collection<? extends ArchiveTipe>)newValue);
        return;
      case MyDslPackage.APPLICATION__FEATURE:
        getFeature().clear();
        getFeature().addAll((Collection<? extends EObject>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.APPLICATION__FEATURES1:
        getFeatures1().clear();
        return;
      case MyDslPackage.APPLICATION__FEATURES:
        getFeatures().clear();
        return;
      case MyDslPackage.APPLICATION__FEATURE:
        getFeature().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.APPLICATION__FEATURES1:
        return features1 != null && !features1.isEmpty();
      case MyDslPackage.APPLICATION__FEATURES:
        return features != null && !features.isEmpty();
      case MyDslPackage.APPLICATION__FEATURE:
        return feature != null && !feature.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //ApplicationImpl
