/**
 * generated by Xtext 2.14.0
 */
package org.xtext;

import org.xtext.HelloStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class HelloStandaloneSetup extends HelloStandaloneSetupGenerated {
  public static void doSetup() {
    new HelloStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
