/*
 * generated by Xtext 2.14.0
 */
package ru.spbstu.application.configurator.model.validation

import org.eclipse.xtext.validation.Check
import ru.spbstu.application.configurator.model.infoProject.Include
import org.eclipse.core.resources.ResourcesPlugin
import org.eclipse.core.runtime.Path


/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class InfoProjectValidator extends AbstractInfoProjectValidator {
		
	
}