/**
 * generated by Xtext 2.14.0
 */
package org.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.HelloRuntimeModule;
import org.xtext.HelloStandaloneSetup;
import org.xtext.ide.HelloIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class HelloIdeSetup extends HelloStandaloneSetup {
  @Override
  public Injector createInjector() {
    HelloRuntimeModule _helloRuntimeModule = new HelloRuntimeModule();
    HelloIdeModule _helloIdeModule = new HelloIdeModule();
    return Guice.createInjector(Modules2.mixin(_helloRuntimeModule, _helloIdeModule));
  }
}
