/*
 * generated by Xtext 2.14.0
 */
package org.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class HelloStandaloneSetup extends HelloStandaloneSetupGenerated {

	def static void doSetup() {
		new HelloStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
